package database

var HeaderTemplate string = `// Code generated by 'project database'
// {{.TableName}}.go contains model for the database table [{{.DbName}}.{{.TableName}}]

package {{.PkgName}}

import (
	"encoding/json"
	"encoding/gob"
	"fmt"
	"strings"
	"github.com/mijia/modelq/gmq"
	"database/sql"
	{{if .ImportTime}}"time"{{end}}
)
`

var StructTemplate string = `type {{.Name}} struct {
	{{range .Fields}}{{.Name}} {{.Type}} {{.JsonMeta}}{{if .Comment}} // {{.Comment}}{{end}}
	{{end}}
}
`
