// Code generated by project
// menu_section.go contains model for the database table [dbname=baseinfo sslmode=disable.menu_section]

package models

import (
	"encoding/json"
	"encoding/gob"
	"fmt"
	"strings"
	"github.com/jmoiron/sqlx"
	"database/sql"
	"time"
)
type MenuSection struct {
	Id int64 `json:"id"`
	RestaurantId int64 `json:"restaurant_id"`
	Name string `json:"name"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
	Creator int64 `json:"creator"`
	Operator int64 `json:"operator"`
	Removed bool `json:"removed"`
	
}

// Start of the MenuSection APIs.

func (obj MenuSection) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<MenuSection Id=%v>", obj.Id)
	} else {
		return string(data)
	}
}

func  QueryById(id int64) (*MenuSection,error){

 	ret:=&MenuSection{}
 	err:=db.Get(ret,"select * from dbname=baseinfo sslmode=disable where id=",id)
 	return ret,err
}

func InsertMenuSection(obj MenuSection) error(){

  db.Exec("insert into dbname=baseinfo sslmode=disable(id,restaurant_id,name,create_time,update_time,creator,operator,removed) values(obj.Id,obj.RestaurantId,obj.Name,obj.CreateTime,obj.UpdateTime,obj.Creator,obj.Operator,obj.Removed)",obj)
  return nil
}

func (obj MenuSection) Get(dbtx gmq.DbTx) (MenuSection, error) {
	filter := MenuSectionObjs.FilterId("=", obj.Id)
	if result, err := MenuSectionObjs.Select().Where(filter).One(dbtx); err != nil {
		return obj, err
	} else {
		return result, nil
	}
}

func (obj MenuSection) Insert(dbtx gmq.DbTx) (MenuSection, error) {
	if result, err := MenuSectionObjs.Insert(obj).Run(dbtx); err != nil {
		return obj, err
	}else {
		if dbtx.DriverName() != "postgres" {
			if id, err := result.LastInsertId(); err != nil {
				return obj, err
			} else {
				obj.Id = id
				return obj, err
			}
		}
		return obj, nil
	}
}

func (obj MenuSection) Update(dbtx gmq.DbTx) (int64, error) {
	fields := []string{ "RestaurantId", "Name", "CreateTime", "UpdateTime", "Creator", "Operator", "Removed" }
	filter := MenuSectionObjs.FilterId("=", obj.Id)
	if result, err := MenuSectionObjs.Update(obj, fields...).Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

func (obj MenuSection) Delete(dbtx gmq.DbTx) (int64, error) {
	filter := MenuSectionObjs.FilterId("=", obj.Id)
	if result, err := MenuSectionObjs.Delete().Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

// Start of the inner Query Api

type _MenuSectionQuery struct {
	gmq.Query
}

func (q _MenuSectionQuery) Where(f gmq.Filter) _MenuSectionQuery {
	q.Query = q.Query.Where(f)
	return q
}

func (q _MenuSectionQuery) OrderBy(by ...string) _MenuSectionQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		sortDir := ""
		if b[0] == '-' || b[0] == '+' {
			sortDir = string(b[0])
			b = b[1:]
		}
		if col, ok := MenuSectionObjs.fcMap[b]; ok {
			tBy = append(tBy, sortDir+col)
		}
	}
	q.Query = q.Query.OrderBy(tBy...)
	return q
}

func (q _MenuSectionQuery) GroupBy(by ...string) _MenuSectionQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		if col, ok := MenuSectionObjs.fcMap[b]; ok {
			tBy = append(tBy, col)
		}
	}
	q.Query = q.Query.GroupBy(tBy...)
	return q
}

func (q _MenuSectionQuery) Limit(offsets ...int64) _MenuSectionQuery {
	q.Query = q.Query.Limit(offsets...)
	return q
}

func (q _MenuSectionQuery) Page(number, size int) _MenuSectionQuery {
	q.Query = q.Query.Page(number, size)
	return q
}

func (q _MenuSectionQuery) Run(dbtx gmq.DbTx) (sql.Result, error) {
	return q.Query.Exec(dbtx)
}

type MenuSectionRowVisitor func(obj MenuSection) bool

func (q _MenuSectionQuery) Iterate(dbtx gmq.DbTx, functor MenuSectionRowVisitor) error {
	return q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := MenuSectionObjs.toMenuSection(columns, rb)
		return functor(obj)
	})
}

func (q _MenuSectionQuery) One(dbtx gmq.DbTx) (MenuSection, error) {
	var obj MenuSection
	err := q.Query.SelectOne(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj = MenuSectionObjs.toMenuSection(columns, rb)
		return true
	})
	return obj, err
}

func (q _MenuSectionQuery) List(dbtx gmq.DbTx) ([]MenuSection, error) {
	result := make([]MenuSection, 0, 10)
	err := q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := MenuSectionObjs.toMenuSection(columns, rb)
		result = append(result, obj)
		return true
	})
	return result, err
}

// Start of the model facade Apis.

type _MenuSectionObjs struct {
	fcMap map[string]string
}

func (o _MenuSectionObjs) Names() (schema, tbl, alias string) {
	return "dbname=baseinfo sslmode=disable", "menu_section", "MenuSection"
}

func (o _MenuSectionObjs) Select(fields ...string) _MenuSectionQuery {
	q := _MenuSectionQuery{}
	if len(fields) == 0 {
		fields = []string{ "Id", "RestaurantId", "Name", "CreateTime", "UpdateTime", "Creator", "Operator", "Removed" }
	}
	q.Query = gmq.Select(o, o.columns(fields...))
	return q
}

func (o _MenuSectionObjs) Insert(obj MenuSection) _MenuSectionQuery {
	q := _MenuSectionQuery{}
	q.Query = gmq.Insert(o, o.columnsWithData(obj, "RestaurantId", "Name", "Creator", "Operator", "Removed"))
	return q
}

func (o _MenuSectionObjs) Update(obj MenuSection, fields ...string) _MenuSectionQuery {
	q := _MenuSectionQuery{}
	q.Query = gmq.Update(o, o.columnsWithData(obj, fields...))
	return q
}

func (o _MenuSectionObjs) Delete() _MenuSectionQuery {
	q := _MenuSectionQuery{}
	q.Query = gmq.Delete(o)
	return q
}


///// Managed Objects Filters definition

func (o _MenuSectionObjs) FilterId(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("id", op, params...)
}


func (o _MenuSectionObjs) FilterRestaurantId(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("restaurant_id", op, params...)
}


func (o _MenuSectionObjs) FilterName(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("name", op, params...)
}


func (o _MenuSectionObjs) FilterCreateTime(op string, p time.Time, ps ...time.Time) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("create_time", op, params...)
}


func (o _MenuSectionObjs) FilterUpdateTime(op string, p time.Time, ps ...time.Time) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("update_time", op, params...)
}


func (o _MenuSectionObjs) FilterCreator(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("creator", op, params...)
}


func (o _MenuSectionObjs) FilterOperator(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("operator", op, params...)
}


func (o _MenuSectionObjs) FilterRemoved(op string, p bool, ps ...bool) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("removed", op, params...)
}



///// Managed Objects Columns definition

func (o _MenuSectionObjs) ColumnId(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"id", value}
}

func (o _MenuSectionObjs) ColumnRestaurantId(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"restaurant_id", value}
}

func (o _MenuSectionObjs) ColumnName(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"name", value}
}

func (o _MenuSectionObjs) ColumnCreateTime(p ...time.Time) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"create_time", value}
}

func (o _MenuSectionObjs) ColumnUpdateTime(p ...time.Time) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"update_time", value}
}

func (o _MenuSectionObjs) ColumnCreator(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"creator", value}
}

func (o _MenuSectionObjs) ColumnOperator(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"operator", value}
}

func (o _MenuSectionObjs) ColumnRemoved(p ...bool) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"removed", value}
}


////// Internal helper funcs

func (o _MenuSectionObjs) newFilter(name, op string, params ...interface{}) gmq.Filter {
	if strings.ToUpper(op) == "IN" {
		return gmq.InFilter(name, params)
	}
	return gmq.UnitFilter(name, op, params[0])
}

func (o _MenuSectionObjs) toMenuSection(columns []gmq.Column, rb []sql.RawBytes) MenuSection {
	obj := MenuSection{}
	if len(columns) == len(rb) {
		for i := range columns {
			switch columns[i].Name {
			case "id":
				obj.Id = gmq.AsInt64(rb[i])
			case "restaurant_id":
				obj.RestaurantId = gmq.AsInt64(rb[i])
			case "name":
				obj.Name = gmq.AsString(rb[i])
			case "create_time":
				obj.CreateTime = gmq.AsTime(rb[i])
			case "update_time":
				obj.UpdateTime = gmq.AsTime(rb[i])
			case "creator":
				obj.Creator = gmq.AsInt64(rb[i])
			case "operator":
				obj.Operator = gmq.AsInt64(rb[i])
			case "removed":
				obj.Removed = gmq.AsBool(rb[i])
			 }
		}
	}
	return obj
}

func (o _MenuSectionObjs) columns(fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "Id":
			data = append(data, o.ColumnId())
		case "RestaurantId":
			data = append(data, o.ColumnRestaurantId())
		case "Name":
			data = append(data, o.ColumnName())
		case "CreateTime":
			data = append(data, o.ColumnCreateTime())
		case "UpdateTime":
			data = append(data, o.ColumnUpdateTime())
		case "Creator":
			data = append(data, o.ColumnCreator())
		case "Operator":
			data = append(data, o.ColumnOperator())
		case "Removed":
			data = append(data, o.ColumnRemoved())
		 }
	}
	return data
}

func (o _MenuSectionObjs) columnsWithData(obj MenuSection, fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "Id":
			data = append(data, o.ColumnId(obj.Id))
		case "RestaurantId":
			data = append(data, o.ColumnRestaurantId(obj.RestaurantId))
		case "Name":
			data = append(data, o.ColumnName(obj.Name))
		case "CreateTime":
			data = append(data, o.ColumnCreateTime(obj.CreateTime))
		case "UpdateTime":
			data = append(data, o.ColumnUpdateTime(obj.UpdateTime))
		case "Creator":
			data = append(data, o.ColumnCreator(obj.Creator))
		case "Operator":
			data = append(data, o.ColumnOperator(obj.Operator))
		case "Removed":
			data = append(data, o.ColumnRemoved(obj.Removed))
		 }
	}
	return data
}

var MenuSectionObjs _MenuSectionObjs

func init() {
	MenuSectionObjs.fcMap = map[string]string{
		"Id": "id",
		"RestaurantId": "restaurant_id",
		"Name": "name",
		"CreateTime": "create_time",
		"UpdateTime": "update_time",
		"Creator": "creator",
		"Operator": "operator",
		"Removed": "removed",
		 }
	gob.Register(MenuSection{})
}
