// Code generated by project
// supplier.go contains model for the database table [dbname=baseinfo sslmode=disable.supplier]

package models

import (
	"encoding/json"
	"encoding/gob"
	"fmt"
	"strings"
	"github.com/jmoiron/sqlx"
	"database/sql"
	"time"
)
type Supplier struct {
	Id int64 `json:"id"`
	Name string `json:"name"`
	Tel string `json:"tel"`
	Type int `json:"type"`
	Images string `json:"images"`
	Location string `json:"location"`
	Address string `json:"address"`
	CityId int64 `json:"city_id"`
	Owners string `json:"owners"`
	DeliveryFee int `json:"delivery_fee"`
	DeliveryRange int `json:"delivery_range"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
	Creator int64 `json:"creator"`
	Operator int64 `json:"operator"`
	Removed bool `json:"removed"`
	Version int `json:"version"`
	
}

// Start of the Supplier APIs.

func (obj Supplier) String() string {
	if data, err := json.Marshal(obj); err != nil {
		return fmt.Sprintf("<Supplier Id=%v>", obj.Id)
	} else {
		return string(data)
	}
}

func  QueryById(id int64) (*Supplier,error){

 	ret:=&Supplier{}
 	err:=db.Get(ret,"select * from dbname=baseinfo sslmode=disable where id=",id)
 	return ret,err
}

func InsertSupplier(obj Supplier) error(){

  db.Exec("insert into dbname=baseinfo sslmode=disable(id,name,tel,type,images,location,address,city_id,owners,delivery_fee,delivery_range,create_time,update_time,creator,operator,removed,version) values(obj.Id,obj.Name,obj.Tel,obj.Type,obj.Images,obj.Location,obj.Address,obj.CityId,obj.Owners,obj.DeliveryFee,obj.DeliveryRange,obj.CreateTime,obj.UpdateTime,obj.Creator,obj.Operator,obj.Removed,obj.Version)",obj)
  return nil
}

func (obj Supplier) Get(dbtx gmq.DbTx) (Supplier, error) {
	filter := SupplierObjs.FilterId("=", obj.Id)
	if result, err := SupplierObjs.Select().Where(filter).One(dbtx); err != nil {
		return obj, err
	} else {
		return result, nil
	}
}

func (obj Supplier) Insert(dbtx gmq.DbTx) (Supplier, error) {
	if result, err := SupplierObjs.Insert(obj).Run(dbtx); err != nil {
		return obj, err
	}else {
		if dbtx.DriverName() != "postgres" {
			if id, err := result.LastInsertId(); err != nil {
				return obj, err
			} else {
				obj.Id = id
				return obj, err
			}
		}
		return obj, nil
	}
}

func (obj Supplier) Update(dbtx gmq.DbTx) (int64, error) {
	fields := []string{ "Name", "Tel", "Type", "Images", "Location", "Address", "CityId", "Owners", "DeliveryFee", "DeliveryRange", "CreateTime", "UpdateTime", "Creator", "Operator", "Removed", "Version" }
	filter := SupplierObjs.FilterId("=", obj.Id)
	if result, err := SupplierObjs.Update(obj, fields...).Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

func (obj Supplier) Delete(dbtx gmq.DbTx) (int64, error) {
	filter := SupplierObjs.FilterId("=", obj.Id)
	if result, err := SupplierObjs.Delete().Where(filter).Run(dbtx); err != nil {
		return 0, err
	} else {
		return result.RowsAffected()
	}
}

// Start of the inner Query Api

type _SupplierQuery struct {
	gmq.Query
}

func (q _SupplierQuery) Where(f gmq.Filter) _SupplierQuery {
	q.Query = q.Query.Where(f)
	return q
}

func (q _SupplierQuery) OrderBy(by ...string) _SupplierQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		sortDir := ""
		if b[0] == '-' || b[0] == '+' {
			sortDir = string(b[0])
			b = b[1:]
		}
		if col, ok := SupplierObjs.fcMap[b]; ok {
			tBy = append(tBy, sortDir+col)
		}
	}
	q.Query = q.Query.OrderBy(tBy...)
	return q
}

func (q _SupplierQuery) GroupBy(by ...string) _SupplierQuery {
	tBy := make([]string, 0, len(by))
	for _, b := range by {
		if col, ok := SupplierObjs.fcMap[b]; ok {
			tBy = append(tBy, col)
		}
	}
	q.Query = q.Query.GroupBy(tBy...)
	return q
}

func (q _SupplierQuery) Limit(offsets ...int64) _SupplierQuery {
	q.Query = q.Query.Limit(offsets...)
	return q
}

func (q _SupplierQuery) Page(number, size int) _SupplierQuery {
	q.Query = q.Query.Page(number, size)
	return q
}

func (q _SupplierQuery) Run(dbtx gmq.DbTx) (sql.Result, error) {
	return q.Query.Exec(dbtx)
}

type SupplierRowVisitor func(obj Supplier) bool

func (q _SupplierQuery) Iterate(dbtx gmq.DbTx, functor SupplierRowVisitor) error {
	return q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := SupplierObjs.toSupplier(columns, rb)
		return functor(obj)
	})
}

func (q _SupplierQuery) One(dbtx gmq.DbTx) (Supplier, error) {
	var obj Supplier
	err := q.Query.SelectOne(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj = SupplierObjs.toSupplier(columns, rb)
		return true
	})
	return obj, err
}

func (q _SupplierQuery) List(dbtx gmq.DbTx) ([]Supplier, error) {
	result := make([]Supplier, 0, 10)
	err := q.Query.SelectList(dbtx, func(columns []gmq.Column, rb []sql.RawBytes) bool {
		obj := SupplierObjs.toSupplier(columns, rb)
		result = append(result, obj)
		return true
	})
	return result, err
}

// Start of the model facade Apis.

type _SupplierObjs struct {
	fcMap map[string]string
}

func (o _SupplierObjs) Names() (schema, tbl, alias string) {
	return "dbname=baseinfo sslmode=disable", "supplier", "Supplier"
}

func (o _SupplierObjs) Select(fields ...string) _SupplierQuery {
	q := _SupplierQuery{}
	if len(fields) == 0 {
		fields = []string{ "Id", "Name", "Tel", "Type", "Images", "Location", "Address", "CityId", "Owners", "DeliveryFee", "DeliveryRange", "CreateTime", "UpdateTime", "Creator", "Operator", "Removed", "Version" }
	}
	q.Query = gmq.Select(o, o.columns(fields...))
	return q
}

func (o _SupplierObjs) Insert(obj Supplier) _SupplierQuery {
	q := _SupplierQuery{}
	q.Query = gmq.Insert(o, o.columnsWithData(obj, "Name", "Tel", "Type", "Images", "Location", "Address", "CityId", "Owners", "DeliveryFee", "DeliveryRange", "Creator", "Operator", "Removed", "Version"))
	return q
}

func (o _SupplierObjs) Update(obj Supplier, fields ...string) _SupplierQuery {
	q := _SupplierQuery{}
	q.Query = gmq.Update(o, o.columnsWithData(obj, fields...))
	return q
}

func (o _SupplierObjs) Delete() _SupplierQuery {
	q := _SupplierQuery{}
	q.Query = gmq.Delete(o)
	return q
}


///// Managed Objects Filters definition

func (o _SupplierObjs) FilterId(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("id", op, params...)
}


func (o _SupplierObjs) FilterName(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("name", op, params...)
}


func (o _SupplierObjs) FilterTel(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("tel", op, params...)
}


func (o _SupplierObjs) FilterType(op string, p int, ps ...int) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("type", op, params...)
}


func (o _SupplierObjs) FilterImages(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("images", op, params...)
}


func (o _SupplierObjs) FilterLocation(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("location", op, params...)
}


func (o _SupplierObjs) FilterAddress(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("address", op, params...)
}


func (o _SupplierObjs) FilterCityId(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("city_id", op, params...)
}


func (o _SupplierObjs) FilterOwners(op string, p string, ps ...string) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("owners", op, params...)
}


func (o _SupplierObjs) FilterDeliveryFee(op string, p int, ps ...int) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("delivery_fee", op, params...)
}


func (o _SupplierObjs) FilterDeliveryRange(op string, p int, ps ...int) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("delivery_range", op, params...)
}


func (o _SupplierObjs) FilterCreateTime(op string, p time.Time, ps ...time.Time) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("create_time", op, params...)
}


func (o _SupplierObjs) FilterUpdateTime(op string, p time.Time, ps ...time.Time) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("update_time", op, params...)
}


func (o _SupplierObjs) FilterCreator(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("creator", op, params...)
}


func (o _SupplierObjs) FilterOperator(op string, p int64, ps ...int64) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("operator", op, params...)
}


func (o _SupplierObjs) FilterRemoved(op string, p bool, ps ...bool) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("removed", op, params...)
}


func (o _SupplierObjs) FilterVersion(op string, p int, ps ...int) gmq.Filter {
	params := make([]interface{}, 1+len(ps))
	params[0] = p
	for i := range ps {
		params[i+1] = ps[i]
	}
	return o.newFilter("version", op, params...)
}



///// Managed Objects Columns definition

func (o _SupplierObjs) ColumnId(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"id", value}
}

func (o _SupplierObjs) ColumnName(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"name", value}
}

func (o _SupplierObjs) ColumnTel(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"tel", value}
}

func (o _SupplierObjs) ColumnType(p ...int) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"type", value}
}

func (o _SupplierObjs) ColumnImages(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"images", value}
}

func (o _SupplierObjs) ColumnLocation(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"location", value}
}

func (o _SupplierObjs) ColumnAddress(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"address", value}
}

func (o _SupplierObjs) ColumnCityId(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"city_id", value}
}

func (o _SupplierObjs) ColumnOwners(p ...string) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"owners", value}
}

func (o _SupplierObjs) ColumnDeliveryFee(p ...int) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"delivery_fee", value}
}

func (o _SupplierObjs) ColumnDeliveryRange(p ...int) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"delivery_range", value}
}

func (o _SupplierObjs) ColumnCreateTime(p ...time.Time) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"create_time", value}
}

func (o _SupplierObjs) ColumnUpdateTime(p ...time.Time) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"update_time", value}
}

func (o _SupplierObjs) ColumnCreator(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"creator", value}
}

func (o _SupplierObjs) ColumnOperator(p ...int64) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"operator", value}
}

func (o _SupplierObjs) ColumnRemoved(p ...bool) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"removed", value}
}

func (o _SupplierObjs) ColumnVersion(p ...int) gmq.Column {
	var value interface{}
	if len(p) > 0 {
		value = p[0]
	}
	return gmq.Column{"version", value}
}


////// Internal helper funcs

func (o _SupplierObjs) newFilter(name, op string, params ...interface{}) gmq.Filter {
	if strings.ToUpper(op) == "IN" {
		return gmq.InFilter(name, params)
	}
	return gmq.UnitFilter(name, op, params[0])
}

func (o _SupplierObjs) toSupplier(columns []gmq.Column, rb []sql.RawBytes) Supplier {
	obj := Supplier{}
	if len(columns) == len(rb) {
		for i := range columns {
			switch columns[i].Name {
			case "id":
				obj.Id = gmq.AsInt64(rb[i])
			case "name":
				obj.Name = gmq.AsString(rb[i])
			case "tel":
				obj.Tel = gmq.AsString(rb[i])
			case "type":
				obj.Type = gmq.AsInt(rb[i])
			case "images":
				obj.Images = gmq.AsString(rb[i])
			case "location":
				obj.Location = gmq.AsString(rb[i])
			case "address":
				obj.Address = gmq.AsString(rb[i])
			case "city_id":
				obj.CityId = gmq.AsInt64(rb[i])
			case "owners":
				obj.Owners = gmq.AsString(rb[i])
			case "delivery_fee":
				obj.DeliveryFee = gmq.AsInt(rb[i])
			case "delivery_range":
				obj.DeliveryRange = gmq.AsInt(rb[i])
			case "create_time":
				obj.CreateTime = gmq.AsTime(rb[i])
			case "update_time":
				obj.UpdateTime = gmq.AsTime(rb[i])
			case "creator":
				obj.Creator = gmq.AsInt64(rb[i])
			case "operator":
				obj.Operator = gmq.AsInt64(rb[i])
			case "removed":
				obj.Removed = gmq.AsBool(rb[i])
			case "version":
				obj.Version = gmq.AsInt(rb[i])
			 }
		}
	}
	return obj
}

func (o _SupplierObjs) columns(fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "Id":
			data = append(data, o.ColumnId())
		case "Name":
			data = append(data, o.ColumnName())
		case "Tel":
			data = append(data, o.ColumnTel())
		case "Type":
			data = append(data, o.ColumnType())
		case "Images":
			data = append(data, o.ColumnImages())
		case "Location":
			data = append(data, o.ColumnLocation())
		case "Address":
			data = append(data, o.ColumnAddress())
		case "CityId":
			data = append(data, o.ColumnCityId())
		case "Owners":
			data = append(data, o.ColumnOwners())
		case "DeliveryFee":
			data = append(data, o.ColumnDeliveryFee())
		case "DeliveryRange":
			data = append(data, o.ColumnDeliveryRange())
		case "CreateTime":
			data = append(data, o.ColumnCreateTime())
		case "UpdateTime":
			data = append(data, o.ColumnUpdateTime())
		case "Creator":
			data = append(data, o.ColumnCreator())
		case "Operator":
			data = append(data, o.ColumnOperator())
		case "Removed":
			data = append(data, o.ColumnRemoved())
		case "Version":
			data = append(data, o.ColumnVersion())
		 }
	}
	return data
}

func (o _SupplierObjs) columnsWithData(obj Supplier, fields ...string) []gmq.Column {
	data := make([]gmq.Column, 0, len(fields))
	for _, f := range fields {
		switch f {
		case "Id":
			data = append(data, o.ColumnId(obj.Id))
		case "Name":
			data = append(data, o.ColumnName(obj.Name))
		case "Tel":
			data = append(data, o.ColumnTel(obj.Tel))
		case "Type":
			data = append(data, o.ColumnType(obj.Type))
		case "Images":
			data = append(data, o.ColumnImages(obj.Images))
		case "Location":
			data = append(data, o.ColumnLocation(obj.Location))
		case "Address":
			data = append(data, o.ColumnAddress(obj.Address))
		case "CityId":
			data = append(data, o.ColumnCityId(obj.CityId))
		case "Owners":
			data = append(data, o.ColumnOwners(obj.Owners))
		case "DeliveryFee":
			data = append(data, o.ColumnDeliveryFee(obj.DeliveryFee))
		case "DeliveryRange":
			data = append(data, o.ColumnDeliveryRange(obj.DeliveryRange))
		case "CreateTime":
			data = append(data, o.ColumnCreateTime(obj.CreateTime))
		case "UpdateTime":
			data = append(data, o.ColumnUpdateTime(obj.UpdateTime))
		case "Creator":
			data = append(data, o.ColumnCreator(obj.Creator))
		case "Operator":
			data = append(data, o.ColumnOperator(obj.Operator))
		case "Removed":
			data = append(data, o.ColumnRemoved(obj.Removed))
		case "Version":
			data = append(data, o.ColumnVersion(obj.Version))
		 }
	}
	return data
}

var SupplierObjs _SupplierObjs

func init() {
	SupplierObjs.fcMap = map[string]string{
		"Id": "id",
		"Name": "name",
		"Tel": "tel",
		"Type": "type",
		"Images": "images",
		"Location": "location",
		"Address": "address",
		"CityId": "city_id",
		"Owners": "owners",
		"DeliveryFee": "delivery_fee",
		"DeliveryRange": "delivery_range",
		"CreateTime": "create_time",
		"UpdateTime": "update_time",
		"Creator": "creator",
		"Operator": "operator",
		"Removed": "removed",
		"Version": "version",
		 }
	gob.Register(Supplier{})
}
